#!/bin/bash

cmake . -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=./ios.toolchain.cmake -DPLATFORM=OS -DCMAKE_SYSTEM_NAME=iOS-simulator -DCMAKE_OSX_SYSROOT=iphoneos -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_SYSTEM_PROCESSOR=arm64 -DIOS_BUILD=1
